### PR TITLE
Clean up imports

### PR DESCRIPTION
**Pull request by leoetlino**
- Remove requireFromRoot, now that there's an "app" module (which is a symlink to the source)

- Switch to ES6-style imports/exports, and remove wrong exports (where a whole object was exported instead of exporting individually)

- Reorder imports and separate modules from ITFrame codebase imports for more readability.

- Also fix any obvious lint errors that shouldn't have been there in the first place.

I didn't fix anything else (var/let vs const) unless I needed to edit the line.

---
This change is [Reviewable](https://reviewable.io/reviews/innovate-technologies/itframe/30)

### CODE REVIEW

**Comment by meyskens** [comment]
@leoetlino LGTM, but maybe should be tested first

**Comment by leoetlino** [comment]
ESLint doesn't complain, so it should be okay.

**Comment by leoetlino** [comment]
If anything, there are now more checks than there were before. But I agree that this should still be tested, probably just by running it.

**Comment by meyskens** [comment]
Merged in #31

**Pull request closed without merging**
