### PR TITLE
Add /control/tunes/update-default-artwork/:username

### PR DESCRIPTION
**Pull request by meyskens**
add /control/tunes/update-default-artwork/:username to update the default artwork as described in #27

---
This change is [Reviewable](https://reviewable.io/reviews/innovate-technologies/itframe/29)

### CODE REVIEW

**Comment by leoetlino** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/tunes/personalMusicDatabase.js, line 105 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/29#-KPgYitg_K9xykklAxgC:-KPgYitg_K9xykklAxgD:bpfyxf3) ([raw file](https://github.com/innovate-technologies/itframe/blob/bfe81eb075c5b6a194038d580f08f90d6cf686fe/components/tunes/personalMusicDatabase.js#L105)):*
> ```JavaScript
> export const setDefaultForUsername = async (username, info) => {
>     let defaultInfo = await TunesPersonalModel.findOne({
>         username: username,
> ```

`username`

---

*[components/tunes/personalMusicDatabase.js, line 108 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/29#-KPgYmohIds3gG1hWJ8e:-KPgYmohIds3gG1hWJ8f:bbixnfe) ([raw file](https://github.com/innovate-technologies/itframe/blob/bfe81eb075c5b6a194038d580f08f90d6cf686fe/components/tunes/personalMusicDatabase.js#L108)):*
> ```JavaScript
>         type: "default",
>     }).exec()
>     if (defaultInfo) {
> ```

`if (!defaultInfo)`?

---

*[http/control/tunes.js, line 135 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/29#-KPgYvmo3NK97lr0_Co7:-KPgYvmo3NK97lr0_Co8:b-f1llvj) ([raw file](https://github.com/innovate-technologies/itframe/blob/bfe81eb075c5b6a194038d580f08f90d6cf686fe/http/control/tunes.js#L135)):*
> ```JavaScript
>         req.log.info({ link: req.file.link }, "Uploaded file");
>         await tunesDB.setDefaultForUsername(req.body.username, { artwork: req.file.link })
>         res.json({})
> ```

I think it may be useful to return the uploaded link.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/29)*

**Comment by meyskens** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[components/tunes/personalMusicDatabase.js, line 105 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/29#-KPgYitg_K9xykklAxgC:-KPgZCmr8jozdy7N1Bhr:b-896fix) ([raw file](https://github.com/innovate-technologies/itframe/blob/bfe81eb075c5b6a194038d580f08f90d6cf686fe/components/tunes/personalMusicDatabase.js#L105)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> `username`
</details>
Done.

---

*[components/tunes/personalMusicDatabase.js, line 108 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/29#-KPgYmohIds3gG1hWJ8e:-KPgZD9pZkLf_H7lYUsB:b-896fix) ([raw file](https://github.com/innovate-technologies/itframe/blob/bfe81eb075c5b6a194038d580f08f90d6cf686fe/components/tunes/personalMusicDatabase.js#L108)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> `if (!defaultInfo)`?
</details>
Done.

---

*[http/control/tunes.js, line 135 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/29#-KPgYvmo3NK97lr0_Co7:-KPgZcjHbrh-rianbT-O:b-896fix) ([raw file](https://github.com/innovate-technologies/itframe/blob/bfe81eb075c5b6a194038d580f08f90d6cf686fe/http/control/tunes.js#L135)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> I think it may be useful to return the uploaded link.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/29)*

**Comment by leoetlino** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[http/control/tunes.js, line 134 \[r2\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/29#-KPgZroOrX0nGQHNStFB:-KPgZroP3cl8WLKVFe5D:b-9577sd) ([raw file](https://github.com/innovate-technologies/itframe/blob/941bcc07d08f9c1199d95d9aedb72a4c74ec34a4/http/control/tunes.js#L134)):*
> ```JavaScript
>         }
>         req.log.info({ link: req.file.link }, "Uploaded file");
>         const link = req.file.link.replace("https://", "https://photon.shoutca.st/")
> ```

photon.innovatete.ch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/29)*

**Comment by leoetlino** [comment]
Really fixup (with git rebase -i) and this should be good to go. :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/29#-:-KPg_DarWgYdnrhPJD7e:bf4p1j2)*

**Pull request merged**
