### PR TITLE
Added validation of TuneIn details by sending a song update

### PR DESCRIPTION
**Pull request by meyskens**
Added validation of TuneIn details by sending a song update, if it fails it will respond with a 500 error to Control to display the error.

---
This change is [Reviewable](https://reviewable.io/reviews/innovate-technologies/itframe/5)

### CODE REVIEW

**Comment by leoetlino** [comment]
Needs to be rebased on master.

**Comment by meyskens** [comment]
GitHub is able to do that these days :)

**Comment by leoetlino** [comment]
It doesn't afaik (and still shows two commits); you still need to manually rebase so we don't end up with a double "remove npm-debug" commit.

**Comment by leoetlino** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[components/nowplaying/tunein.js, line 79 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/5#-KJVNu4oNEhBjtQZ0oSj:-KJVNu4oNEhBjtQZ0oSk:-822560076) ([raw file](https://github.com/innovate-technologies/itframe/blob/0a709a737859e9c5d307bc9d24f9f25e28ea40e0/components/nowplaying/tunein.js#L79)):*
> ```JavaScript
>     }).on("complete", function (response, info) {
>         if (response instanceof Error) {
>             return callback("Invalid details provided for TuneIn AIR")
> ```

The first argument for standard callbacks should be an `Error`

---

*[components/nowplaying/tunein.js, line 83 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/5#-KJVO23sB-RY1iGNjn08:-KJVO23sB-RY1iGNjn09:-469765787) ([raw file](https://github.com/innovate-technologies/itframe/blob/0a709a737859e9c5d307bc9d24f9f25e28ea40e0/components/nowplaying/tunein.js#L83)):*
> ```JavaScript
>         if (typeof response === "string" && response.includes("<status>403</status>")
>                 || info.statusCode === 403) {
>             return callback("Invalid details provided for TuneIn AIR");
> ```

ditto

---

*[components/nowplaying/tunein.js, line 85 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/5#-KJVO3no3AEWWl_Bn4il:-KJVO3no3AEWWl_Bn4im:576092875) ([raw file](https://github.com/innovate-technologies/itframe/blob/0a709a737859e9c5d307bc9d24f9f25e28ea40e0/components/nowplaying/tunein.js#L85)):*
> ```JavaScript
>             return callback("Invalid details provided for TuneIn AIR");
>         }
>         callback(null)
> ```

callback()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/5)*

**Comment by meyskens** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[components/nowplaying/tunein.js, line 79 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/5#-KJVNu4oNEhBjtQZ0oSj:-KJVP4l6NPqW52F3MkDG:-499146009) ([raw file](https://github.com/innovate-technologies/itframe/blob/0a709a737859e9c5d307bc9d24f9f25e28ea40e0/components/nowplaying/tunein.js#L79)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> The first argument for standard callbacks should be an `Error`
</details>
Done.

---

*[components/nowplaying/tunein.js, line 83 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/5#-KJVO23sB-RY1iGNjn08:-KJVP57Q6ha60ERZgdzw:-499146009) ([raw file](https://github.com/innovate-technologies/itframe/blob/0a709a737859e9c5d307bc9d24f9f25e28ea40e0/components/nowplaying/tunein.js#L83)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> ditto
</details>
Done.

---

*[components/nowplaying/tunein.js, line 85 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/5#-KJVO3no3AEWWl_Bn4il:-KJVP5cOVgY5S6MJpw8K:-499146009) ([raw file](https://github.com/innovate-technologies/itframe/blob/0a709a737859e9c5d307bc9d24f9f25e28ea40e0/components/nowplaying/tunein.js#L85)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> callback()
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/5)*

**Comment by leoetlino** [comment]
:lgtm:

<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> It doesn't afaik (and still shows two commits); you still need to manually rebase so we don't end up with a double "remove npm-debug" commit.
</details>


---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/5#-:-KJVVbC4fw8tumtB2C6n:1417088721)*

**Comment by meyskens** [comment]
Uhm... dear git, why those other 2 again?

**Comment by leoetlino** [comment]
You have to rebase and squash.

**Pull request merged**
