### PR TITLE
Add antiStreamRipper and hideListenerCount

### PR DESCRIPTION
**Pull request by meyskens**
Add extra Cast features like antiStreamRipper and hideListenerCount. This code is still in wait.for syntax to keep consistency (to be rewritten in a later refactor PR)

---
This change is [Reviewable](https://reviewable.io/reviews/innovate-technologies/itframe/14)

### CODE REVIEW

**Comment by leoetlino** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/cast/database.js, line 64 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/14#-KNcl09zDMnSU4RWPgfr:-KNcl09zDMnSU4RWPgfs:-1041951463) ([raw file](https://github.com/innovate-technologies/itframe/blob/d9945ee89eeaba0b937fb72d1b615057c3b50825/components/cast/database.js#L64)):*
> ```JavaScript
>         mode: { type: String, enum: ["blacklist", "whitelist"] },
>     },
>     antiStreamRipper: {
> ```

maybe… enableStreamRipper to be clearer?

---

*[http/control/cast.js, line 154 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/14#-KNclOw1h3tiSj_TPmmk:-KNclOw1h3tiSj_TPmml:-22201460) ([raw file](https://github.com/innovate-technologies/itframe/blob/d9945ee89eeaba0b937fb72d1b615057c3b50825/http/control/cast.js#L154)):*
> ```JavaScript
>     });
> 
>     app.del("/control/cast/anti-stream-ripper/:username", (req, res, next) => {
> ```

shouldn't this be .delete?

Anyway, I think we don't really need this. I'd suggest merging this with the above and accepting req.body.isEnabled.

---

*[http/control/cast.js, line 180 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/14#-KNclDdaL1WdMR4EJ2WR:-KNclDdaL1WdMR4EJ2WS:1422984132) ([raw file](https://github.com/innovate-technologies/itframe/blob/d9945ee89eeaba0b937fb72d1b615057c3b50825/http/control/cast.js#L180)):*
> ```JavaScript
>     });
> 
>     app.del("/control/cast/hide-listener-count/:username", (req, res, next) => {
> ```

same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/14)*

**Comment by meyskens** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/cast/database.js, line 64 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/14#-KNcl09zDMnSU4RWPgfr:-KNf92JSZCtb_Pn1rTqj:1595295510) ([raw file](https://github.com/innovate-technologies/itframe/blob/d9945ee89eeaba0b937fb72d1b615057c3b50825/components/cast/database.js#L64)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> maybe… enableStreamRipper to be clearer?
</details>
Has to match Cast's configuration

---

*[http/control/cast.js, line 154 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/14#-KNclOw1h3tiSj_TPmmk:-KNf96EIMl-bGVjQUaF9:473675083) ([raw file](https://github.com/innovate-technologies/itframe/blob/d9945ee89eeaba0b937fb72d1b615057c3b50825/http/control/cast.js#L154)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> shouldn't this be .delete?
> 
> Anyway, I think we don't really need this. I'd suggest merging this with the above and accepting req.body.isEnabled.
</details>
True, was confused with another plugin where they used .del instead of delete
and +1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/14)*

**Comment by leoetlino** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/14)*

**Comment by leoetlino** [comment]
:lgtm:
Feel free to merge after squashing.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/14#-:-KNqYblQIxWUgmpJlEZQ:1525307433)*

**Pull request merged**
