### PR TITLE
Control: Add support routes

### PR DESCRIPTION
**Pull request by leoetlino**
Adds support routes for Control.

* [x] getTicket
* [x] getTickets
* [x] changeStatusForTicket: what statuses to allow? Only Customer-Reply and closed?
* [x] getRepliesForTicket
* [x] postReplyForTicket
* [x] openTicket

---
This change is [Reviewable](https://reviewable.io/reviews/innovate-technologies/itframe/13)

### CODE REVIEW

**Comment by leoetlino** [comment]
Should be feature complete now.

**Comment by meyskens** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[http/control/support.js, line 9 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/13#-KNfgHFz64-E9GlTjRhn:-KNfgHG-1pSY-luzDmFe:1148134098) ([raw file](https://github.com/innovate-technologies/itframe/blob/25c95cd4c65aeddf73fe860a26de5c1e15715666/http/control/support.js#L9)):*
> ```JavaScript
>         const ticketIdToCheck = req.params.ticketId;
>         if (!ticketIdToCheck) {
>             next();
> ```

why not `return next()`

---

*[http/control/support.js, line 49 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/13#-KNfgj7LmM-jw8k8uN3z:-KNfgj7LmM-jw8k8uN4-:-2100718615) ([raw file](https://github.com/innovate-technologies/itframe/blob/25c95cd4c65aeddf73fe860a26de5c1e15715666/http/control/support.js#L49)):*
> ```JavaScript
>     app.put("/control/support/tickets/:ticketId/status", wrap(async function (req, res) {
>         const newStatus = req.body;
>         if (ALLOWED_STATUSES.indexOf(newStatus) === -1) {
> ```

.contains()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/13)*

**Comment by meyskens** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/13)*

**Comment by leoetlino** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[http/control/support.js, line 9 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/13#-KNfgHFz64-E9GlTjRhn:-KNqUsLk1pFe7H4eIh2k:1158557434) ([raw file](https://github.com/innovate-technologies/itframe/blob/25c95cd4c65aeddf73fe860a26de5c1e15715666/http/control/support.js#L9)):*
<details><summary><i>Previously, meyskens (Maartje Eyskens) wrote…</i></summary>
> why not `return next()`
</details>
I'm not sure what `next()` returns, and well, after working a bit with statically languages, I'm become more concerned about things like this and believe that `next(); return;` is more correct ;)

---

*[http/control/support.js, line 49 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/13#-KNfgj7LmM-jw8k8uN3z:-KNqWJoZezlKPH-dEKYJ:-1978485883) ([raw file](https://github.com/innovate-technologies/itframe/blob/25c95cd4c65aeddf73fe860a26de5c1e15715666/http/control/support.js#L49)):*
<details><summary><i>Previously, meyskens (Maartje Eyskens) wrote…</i></summary>
> .contains()
</details>
hmm, wasn't sure that this worked for arrays as well (in what we enable in Babel -- ES6 doesn't have this). Will change it over.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/13)*

**Comment by meyskens** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[http/control/support.js, line 49 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/13#-KNfgj7LmM-jw8k8uN3z:-KNqWwxN1hXr0caOaCi8:366016524) ([raw file](https://github.com/innovate-technologies/itframe/blob/25c95cd4c65aeddf73fe860a26de5c1e15715666/http/control/support.js#L49)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> hmm, wasn't sure that this worked for arrays as well (in what we enable in Babel -- ES6 doesn't have this). Will change it over.
</details>
I tested this somewhere yesterday and it did not work, but I guess it was not with babel setup.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/13)*

**Comment by meyskens** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/13#-:-KNqX7iul1WkVPCmXd85:1417088721)*

**Comment by leoetlino** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[http/control/support.js, line 49 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/13#-KNfgj7LmM-jw8k8uN3z:-KNqX6bm3mY4tRRwmAWj:-2139737979) ([raw file](https://github.com/innovate-technologies/itframe/blob/25c95cd4c65aeddf73fe860a26de5c1e15715666/http/control/support.js#L49)):*
<details><summary><i>Previously, meyskens (Maartje Eyskens) wrote…</i></summary>
> I tested this somewhere yesterday and it did not work, but I guess it was not with babel setup.
</details>
I'm pretty sure it is; because Array.prototype.includes is not part of the ES6 spec (unlike String.prototype.includes), but ES7 or something else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/13)*

**Comment by meyskens** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/13)*

**Pull request merged**
