### PR TITLE
Routes needed for DJ

### PR DESCRIPTION
**Pull request by meyskens**
Adding extra routes needed for the DJ frontend.
*Needs testing*

- [x] Convert all existing DBs to async/await to speed up development
- [x] Add PATCH routes to update the database
- [x] Add PUT routes to add to the database
- [x] Implement a reload call to DJ
- [x] Add a get queue route
- [x] Add skip song route

---
This change is [Reviewable](https://reviewable.io/reviews/innovate-technologies/itframe/11)

### CODE REVIEW

**Comment by meyskens** [comment]
From what is planned this PR is ready for review.

**Comment by leoetlino** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 22 unresolved discussions.

---

*[components/cast/database.js, line 75 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcbzFFwWO3NyS4ARXJ:-KNcbzFFwWO3NyS4ARXK:1505678631) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/cast/database.js#L75)):*
> ```JavaScript
> }
> ```

Unnecessary change. :P

---

*[components/dj/clocks.js, line 28 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcc85PvBbSxaORBVC6:-KNcc85PvBbSxaORBVC7:1958808602) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/clocks.js#L28)):*
> ```JavaScript
> 
> export const clocksForUsername = (username) => new Promise((resolve, reject) => {
>     ClocksModel.find({username: username}, (err, res) => { err ? reject(err) : resolve(res)})
> ```

can't this just return ClocksModel.find().exec(), as Mongoose has support for promises?

---

*[components/dj/clocks.js, line 34 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNccHL3_7JiUbnxalxn:-KNccHL4wRt4TaRL4eT3:-149221371) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/clocks.js#L34)):*
> ```JavaScript
>     ClocksModel.findOne({
>         _id: new ObjectId(id),
>     }, (err, res) => { err ? reject(err) : resolve(res)})
> ```

same here

---

*[components/dj/clocks.js, line 41 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNccI8Lgo9nVgXIBnKF:-KNccI8Lgo9nVgXIBnKG:1179194526) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/clocks.js#L41)):*
> ```JavaScript
>         _id: new ObjectId(id),
>         username: username,
>     }, (err, res) => { err ? reject(err) : resolve(res)})
> ```

and here

---

*[components/dj/clocks.js, line 46 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcccPUnJ6NkaBbHkIc:-KNcccPUnJ6NkaBbHkId:379069127) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/clocks.js#L46)):*
> ```JavaScript
> export const addClock = (clock) => new Promise((resolve, reject) => {
>     return new ClocksModel(clock).save((err) => {
>         err ? reject(err) : resolve()
> ```

I think .save doesn't need .exec, but not sure.

---

*[components/dj/clocks.js, line 51 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNccfThmvj38sHEN268:-KNccfThmvj38sHEN269:-149221371) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/clocks.js#L51)):*
> ```JavaScript
> 
> export const deleteClockWithID = (id) => new Promise((resolve, reject) => {
>     return ClocksModel.remove({ id }, (err) => {
> ```

same here

---

*[components/dj/clocks.js, line 57 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcchNtc-UqS6vbvC4p:-KNcchNtc-UqS6vbvC4q:1179194526) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/clocks.js#L57)):*
> ```JavaScript
> 
> export const deleteClockWithUsername = (username) => new Promise((resolve, reject) => {
>     return ClocksModel.remove({ username }, (err) => {
> ```

and here

---

*[components/dj/intervals.js, line 30 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNccuB4Ihg-1o2AQxxD:-KNccuB4Ihg-1o2AQxxE:1763574468) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/intervals.js#L30)):*
> ```JavaScript
> 
> export const intervalsForUsername = (username) => new Promise((resolve, reject) => {
>     IntervalsModel.find({ username: username }, (err, res) => { err ? reject(err) : resolve(res)})
> ```

here too. (Also the braces should not be needed)
and below.

---

*[components/dj/intervals.js, line 64 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcdCK-ZRWyB8CjYynx:-KNcdCK-ZRWyB8CjYyny:1930723922) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/intervals.js#L64)):*
> ```JavaScript
>         res = _.extend(res, interval)
>         res.username = username
>         res.save((error) => { error ? reject(error) : resolve() })
> ```

I think you can just resolve this with the promise returned by res.save.

---

*[components/dj/intervals.js, line 66 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcd56Yq3W7Ih1F_pxB:-KNcd56Yq3W7Ih1F_pxC:514113309) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/intervals.js#L66)):*
> ```JavaScript
>         res.save((error) => { error ? reject(error) : resolve() })
>     })
> })
> ```

missing final new line

---

*[http/control/dj.js, line 47 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcdpzKCv7t_uFZtoAa:-KNcdpzKCv7t_uFZtoAb:322948653) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/http/control/dj.js#L47)):*
> ```JavaScript
>     app.post("/control/cast/dj/skip/:username", wrap(async (req, res) => {
>         dj.skipSong(req.params.username)
>         res.json({status: "ok"})
> ```

space after { and before }

---

*[http/control/dj.js, line 59 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcdeYIBXfG-z1rc8mQ:-KNcdeYJsqBdXuQe5QTR:915039454) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/http/control/dj.js#L59)):*
> ```JavaScript
> 
>     app.put("/control/cast/dj/clocks/:username", wrap(async (req, res) => {
>         await clocks.replaceClocksForUsername(req.params.username, req.params.clocks)
> ```

there's no :clocks in the URL.

---

*[http/control/dj.js, line 72 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcdkD9QO9EFxSlEMWJ:-KNcdkD9QO9EFxSlEMWK:545881268) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/http/control/dj.js#L72)):*
> ```JavaScript
> 
>     app.patch("/control/cast/dj/intervals/:username/:id", wrap(async (req, res) => {
>         await intervals.updateIntervalWithUsernameAndID(req.params.username, req.params.interval._id, req.params.interval)
> ```

there is no :interval param here. Perhaps you meant req.body?

---

*[http/control/dj.js, line 74 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcdvj1waHJ7npE5lsq:-KNcdvj1waHJ7npE5lsr:322948653) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/http/control/dj.js#L74)):*
> ```JavaScript
>         await intervals.updateIntervalWithUsernameAndID(req.params.username, req.params.interval._id, req.params.interval)
>         await dj.reloadClocks(req.params.username)
>         res.json({status: "ok"})
> ```

space after { and before }

---

*[http/control/dj.js, line 78 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcdzBrFfnZ-_8nAYJ8:-KNcdzBrFfnZ-_8nAYJ9:1032757891) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/http/control/dj.js#L78)):*
> ```JavaScript
> 
>     app.put("/control/cast/dj/intervals/:username", wrap(async (req, res) => {
>         await intervals.addNewIntervalForUsername(res.params.username, req.params.interval)
> ```

same, probably req.body.interval

---

*[http/control/dj.js, line 80 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcdyh3U0VTQwRGtvgx:-KNcdyh3U0VTQwRGtvgy:322948653) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/http/control/dj.js#L80)):*
> ```JavaScript
>         await intervals.addNewIntervalForUsername(res.params.username, req.params.interval)
>         await dj.reloadClocks(req.params.username)
>         res.json({status: "ok"})
> ```

space after { and before }

---

*[http/dj/clocks.js, line 3 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNce3jgtnLkdbNu1hkC:-KNce3jgtnLkdbNu1hkD:1878101604) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/http/dj/clocks.js#L3)):*
> ```JavaScript
> import * as clocksDB from "../../components/dj/clocks.js"
> 
> module.exports = ({ app }) => {
> ```

while you're at it, just `export default`

---

*[http/dj/clocks.js, line 4 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNce89ZL7nOjC7JSC0t:-KNce89ZL7nOjC7JSC0u:-1917807130) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/http/dj/clocks.js#L4)):*
> ```JavaScript
> 
> module.exports = ({ app }) => {
>     app.get("/dj/:user/:key/all-clocks/", async (req, res, next) => {
> ```

`wrap(async…`, then you can get rid of the try/catch (and be sure any rejections will be handled)

---

*[http/dj/clocks.js, line 11 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNceI4_MsWiS18yG7FW:-KNceI4_MsWiS18yG7FX:-1684574294) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/http/dj/clocks.js#L11)):*
> ```JavaScript
>         }
>     })
>     app.get("/dj/:user/:key/clock/:id/", async (req, res, next) => {
> ```

same here, then you can reduce this function to a check (`throw`) and to a `res.json()`.

---

*[http/dj/intervals.js, line 1 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNceVu3iyh-zzLhIUQK:-KNceVu3iyh-zzLhIUQL:-1292451195) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/http/dj/intervals.js#L1)):*
> ```JavaScript
> import * as intervalsDB from "../../components/dj/intervals.js"
> ```

You can import from the project root with "~/components/…"

---

*[http/dj/intervals.js, line 4 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNceU4N0G5AVilcHOVX:-KNceU4OKyZkBIzbuvHj:-39787531) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/http/dj/intervals.js#L4)):*
> ```JavaScript
> 
> module.exports = function ({ app }) {
>     app.get("/dj/:user/:key/all-intervals/", async (req, res, next) => {
> ```

Just `wrap()` so you don't need to try/catch manually which is error prone and longer.

---

*[http/dj/intervals.js, line 12 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcegODJ51kDoUmaOAZ:-KNcegOEKbyOfOF97iE4:678021867) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/http/dj/intervals.js#L12)):*
> ```JavaScript
>     })
> 
>     app.get("/dj/:user/:key/interval/:id/", (req, res, next) => {
> ```

same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/11)*

**Comment by meyskens** [comment]
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

*[components/dj/clocks.js, line 28 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcc85PvBbSxaORBVC6:-KNgTLzlkQW6tPGaMRK_:-499146009) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/clocks.js#L28)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> can't this just return ClocksModel.find().exec(), as Mongoose has support for promises?
</details>
Done.

---

*[components/dj/clocks.js, line 46 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcccPUnJ6NkaBbHkIc:-KNgTPUM-kRBYMkDcnPl:-1871377228) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/clocks.js#L46)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> I think .save doesn't need .exec, but not sure.
</details>
where is the .exec() you see?

---

*[http/control/dj.js, line 59 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcdeYIBXfG-z1rc8mQ:-KNgVoTuiTHxfmuxCY1Q:-657858943) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/http/control/dj.js#L59)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> there's no :clocks in the URL.
</details>
Replaced with req.body

---

*[http/control/dj.js, line 72 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcdkD9QO9EFxSlEMWJ:-KNgVrfUqOsg02YwLzi8:160424895) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/http/control/dj.js#L72)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> there is no :interval param here. Perhaps you meant req.body?
</details>
yep

---

*[http/dj/intervals.js, line 1 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNceVu3iyh-zzLhIUQK:-KNgWROb9rlF_JfypZ8Y:230276536) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/http/dj/intervals.js#L1)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> You can import from the project root with "~/components/…"
</details>
ESLint dislikes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/11)*

**Comment by leoetlino** [comment]
Review status: 2 of 7 files reviewed at latest revision, 21 unresolved discussions.

---

*[components/dj/clocks.js, line 28 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcc85PvBbSxaORBVC6:-KO135Wt_9_FSpBlxz-y:1926839987) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/clocks.js#L28)):*
<details><summary><i>Previously, meyskens (Maartje Eyskens) wrote…</i></summary>
> Done.
</details>
You need .exec() so it returns a promise. Also async isn't necessary if you directly return a promise

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/11)*

**Comment by leoetlino** [comment]
Reviewed 3 of 5 files at r2.
Review status: 5 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[http/dj/intervals.js, line 1 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNceVu3iyh-zzLhIUQK:-KO15oprScDkQk52AIYa:-834761009) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/http/dj/intervals.js#L1)):*
<details><summary><i>Previously, meyskens (Maartje Eyskens) wrote…</i></summary>
> ESLint dislikes
</details>
but it works ;)
(it's a custom syntax, which is why it doesn't understand it.)
Oh well, this is not very important.

---

*[http/dj/intervals.js, line 3 \[r2\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KO15xeZ7tpg5_JrgB3W:-KO15xeZ7tpg5_JrgB3X:-406980070) ([raw file](https://github.com/innovate-technologies/itframe/blob/40105b12ea234aa947ae2d776b230a6f34f4d543/http/dj/intervals.js#L3)):*
> ```JavaScript
> import * as intervalsDB from "../../components/dj/intervals.js"
> 
> module.exports = function ({ app, wrap }) {
> ```

export default

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/11)*

**Comment by meyskens** [comment]
Review status: 4 of 7 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[components/dj/clocks.js, line 28 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcc85PvBbSxaORBVC6:-KO16SgdenkshG9pK46r:-499146009) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/clocks.js#L28)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> You need .exec() so it returns a promise. Also async isn't necessary if you directly return a promise
</details>
Done.

---

*[components/dj/clocks.js, line 34 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNccHL3_7JiUbnxalxn:-KO14zrO-r72xeVKgWSz:-499146009) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/clocks.js#L34)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> same here
</details>
Done.

---

*[components/dj/clocks.js, line 41 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNccI8Lgo9nVgXIBnKF:-KO15-CdAGmw7IwKcbI1:-499146009) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/clocks.js#L41)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> and here
</details>
Done.

---

*[components/dj/clocks.js, line 46 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcccPUnJ6NkaBbHkIc:-KO15-rlPiYFzVbODxP1:-499146009) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/clocks.js#L46)):*
<details><summary><i>Previously, meyskens (Maartje Eyskens) wrote…</i></summary>
> where is the .exec() you see?
</details>
Done.

---

*[components/dj/clocks.js, line 51 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNccfThmvj38sHEN268:-KO150Xg1rczDIT6IwcF:-499146009) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/clocks.js#L51)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> same here
</details>
Done.

---

*[components/dj/clocks.js, line 57 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcchNtc-UqS6vbvC4p:-KO150vQoBcJk1kGPQk9:-499146009) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/clocks.js#L57)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> and here
</details>
Done.

---

*[components/dj/intervals.js, line 64 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNcdCK-ZRWyB8CjYynx:-KO16X8raV2uv991Tc8n:-499146009) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/intervals.js#L64)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> I think you can just resolve this with the promise returned by res.save.
</details>
Done.

---

*[http/dj/intervals.js, line 1 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KNceVu3iyh-zzLhIUQK:-KO16Zu46noMdWxmKtNL:469015648) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/http/dj/intervals.js#L1)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> but it works ;)
> (it's a custom syntax, which is why it doesn't understand it.)
> Oh well, this is not very important.
</details>
I prefer no red lines, we should add an ignore for that if possible

---

*[http/dj/intervals.js, line 3 \[r2\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KO15xeZ7tpg5_JrgB3W:-KO16jxcEcl1T3uAN0fz:-499146009) ([raw file](https://github.com/innovate-technologies/itframe/blob/40105b12ea234aa947ae2d776b230a6f34f4d543/http/dj/intervals.js#L3)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> export default
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/11)*

**Comment by leoetlino** [comment]
Essentially :lgtm:, apart from some minor things

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[components/dj/intervals.js, line 42 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KO1UVz4OqKV88uv3R1o:-KO1UVz4OqKV88uv3R1p:281354393) ([raw file](https://github.com/innovate-technologies/itframe/blob/3ddd9b79dbfb1c351ab64b362c7e9c5ed2563da5/components/dj/intervals.js#L42)):*
> ```JavaScript
>     IntervalsModel.findOne({
>         _id: new ObjectId(id),
>         username: username,
> ```

can just be `username`. But this isn't very important, feel free to ignore

---

*[http/dj/intervals.js, line 3 \[r2\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KO15xeZ7tpg5_JrgB3W:-KO1UnGxhBXR2sTCPoDs:-348683145) ([raw file](https://github.com/innovate-technologies/itframe/blob/40105b12ea234aa947ae2d776b230a6f34f4d543/http/dj/intervals.js#L3)):*
<details><summary><i>Previously, meyskens (Maartje Eyskens) wrote…</i></summary>
> Done.
</details>
are you sure? :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-:-KO1UrR247T6YoOn7ul2:-488151716)*

**Comment by leoetlino** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[http/dj/intervals.js, line 3 \[r2\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/11#-KO15xeZ7tpg5_JrgB3W:-KO1VhVLSggD1HVOv3Xg:964349108) ([raw file](https://github.com/innovate-technologies/itframe/blob/40105b12ea234aa947ae2d776b230a6f34f4d543/http/dj/intervals.js#L3)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary>
> are you sure? :)
</details>
Looks like Reviewable missed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/11)*

**Pull request merged**
