### PR TITLE
controlUser: Switch to async/await

### PR DESCRIPTION
**Pull request by leoetlino**
This change is [Reviewable](https://reviewable.io/reviews/innovate-technologies/itframe/8)

### CODE REVIEW

**Comment by meyskens** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[components/control/controlUser.js, line 39 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/8#-KLw5uBGEi_xDpkmrq7q:-KLw5uBGEi_xDpkmrq7r:1025904155) ([raw file](https://github.com/innovate-technologies/itframe/blob/37338f7cde84cef60cddb99f4dd43be8814de513/components/control/controlUser.js#L39)):*
> ```JavaScript
>  * @param  {String}   options.subject      Ticket subject
>  * @param  {String}   options.message      Ticket message
>  * @param  {Boolean}  options.sendEmail    Send an email about the ticket to the client
> ```

No @return here? 

---

*[components/legacy/whmcs.js, line 20 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/8#-KLw6jrGyzYZcQrwVEoZ:-KLw6jrGyzYZcQrwVEo_:1080762631) ([raw file](https://github.com/innovate-technologies/itframe/blob/37338f7cde84cef60cddb99f4dd43be8814de513/components/legacy/whmcs.js#L20)):*
> ```JavaScript
>     rest.post(`${config.whmcsURL}/includes/api.php`, {
>         data,
>         rejectUnauthorized: false,
> ```

Probably got there for a dev server, should be removed for security

---

*[components/legacy/whmcs.js, line 75 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/8#-KLw7ZU2HT5H2gSlAteL:-KLw7ZU2HT5H2gSlAteM:2102652983) ([raw file](https://github.com/innovate-technologies/itframe/blob/37338f7cde84cef60cddb99f4dd43be8814de513/components/legacy/whmcs.js#L75)):*
> ```JavaScript
>             company: data.companyname,
>             phone: data.phonenumberformatted,
>             address: data.address1 + "\n" + data.address2 + "\n" + data.city,
> ```

backtick string?

---

*[components/legacy/whmcs.js, line 118 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/8#-KLw7peFULPxnKltgZtZ:-KLw7peFULPxnKltgZt_:-1441303467) ([raw file](https://github.com/innovate-technologies/itframe/blob/37338f7cde84cef60cddb99f4dd43be8814de513/components/legacy/whmcs.js#L118)):*
> ```JavaScript
>     } catch (error) {
>         error.message = "Failed to get products: " + error.message;
>         throw error;
> ```

Maybe log these?

---

*[components/legacy/whmcs.js, line 134 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/8#-KLw80vBoC75KeTFOXxX:-KLw80vBoC75KeTFOXxY:678021867) ([raw file](https://github.com/innovate-technologies/itframe/blob/37338f7cde84cef60cddb99f4dd43be8814de513/components/legacy/whmcs.js#L134)):*
> ```JavaScript
>     } catch (error) {
>         error.message = "Failed to open ticket: " + error.message;
>         throw error;
> ```

same

---

*[http/control/00-security.js, line 140 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/8#-KLwBcVdL5jZefwwNSIh:-KLwBcVdL5jZefwwNSIi:1124153125) ([raw file](https://github.com/innovate-technologies/itframe/blob/37338f7cde84cef60cddb99f4dd43be8814de513/http/control/00-security.js#L140)):*
> ```JavaScript
>         const token = jwt.sign({ email: data.email }, cert, {
>             expiresInMinutes: 120,
>             audience: "https://itframe.shoutca.st/control",
> ```

innovatete.ch 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/8)*

**Comment by leoetlino** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[components/control/controlUser.js, line 39 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/8#-KLw5uBGEi_xDpkmrq7q:-KM0_xEpAq8MhTU6ilA8:997738938) ([raw file](https://github.com/innovate-technologies/itframe/blob/37338f7cde84cef60cddb99f4dd43be8814de513/components/control/controlUser.js#L39)):*
<details><summary><i>Previously, meyskens (Maartje Eyskens) wrote…</i></summary>
> No @return here? 
</details>
The promise doesn't resolve to anything, so no, no at-return.

---

*[components/legacy/whmcs.js, line 20 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/8#-KLw6jrGyzYZcQrwVEoZ:-KM0a315II5Xyfh_NUuQ:203353683) ([raw file](https://github.com/innovate-technologies/itframe/blob/37338f7cde84cef60cddb99f4dd43be8814de513/components/legacy/whmcs.js#L20)):*
<details><summary><i>Previously, meyskens (Maartje Eyskens) wrote…</i></summary>
> Probably got there for a dev server, should be removed for security
</details>
Will be done in a follow-up PR.

---

*[components/legacy/whmcs.js, line 75 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/8#-KLw7ZU2HT5H2gSlAteL:-KM0bj35AOKrgUupnT39:-499146009) ([raw file](https://github.com/innovate-technologies/itframe/blob/37338f7cde84cef60cddb99f4dd43be8814de513/components/legacy/whmcs.js#L75)):*
<details><summary><i>Previously, meyskens (Maartje Eyskens) wrote…</i></summary>
> backtick string?
</details>
Done.

---

*[components/legacy/whmcs.js, line 118 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/8#-KLw7peFULPxnKltgZtZ:-KM0a9wXzMsSsFIDj0I1:1217421736) ([raw file](https://github.com/innovate-technologies/itframe/blob/37338f7cde84cef60cddb99f4dd43be8814de513/components/legacy/whmcs.js#L118)):*
<details><summary><i>Previously, meyskens (Maartje Eyskens) wrote…</i></summary>
> Maybe log these?
</details>
They will be logged in the HTTP handlers, no point in logging it twice :)

---

*[http/control/00-security.js, line 140 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/8#-KLwBcVdL5jZefwwNSIh:-KM0aIstwxOpYKbrWE36:577240747) ([raw file](https://github.com/innovate-technologies/itframe/blob/37338f7cde84cef60cddb99f4dd43be8814de513/http/control/00-security.js#L140)):*
<details><summary><i>Previously, meyskens (Maartje Eyskens) wrote…</i></summary>
> innovatete.ch 
</details>
If this needs a change, it will be in another PR. (btw, I'm not sure if that would cause any issues?) This one is only about replacing wait.for with async/await.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/8)*

**Comment by meyskens** [comment]
Reviewed 6 of 7 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/8)*

**Comment by meyskens** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/legacy/whmcs.js, line 134 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/itframe/8#-KLw80vBoC75KeTFOXxX:-KM_toHpxtrYcaNzMuIR:5173665) ([raw file](https://github.com/innovate-technologies/itframe/blob/37338f7cde84cef60cddb99f4dd43be8814de513/components/legacy/whmcs.js#L134)):*
<details><summary><i>Previously, meyskens (Maartje Eyskens) wrote…</i></summary>
> same
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/8)*

**Comment by meyskens** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/itframe/8#-:-KM_u18IVeVFqUFUl1vI:1417088721)*

**Pull request merged**
